### ISSUE TITLE
Beautify/UX-ify the Site

### ISSUE THREAD

**Issue by GFLEMING133** [msoe-sse/jekyll-post-editor#21]
The site looks very plain in its current form. Although functional, it doesn't spell out "WE-ROCK-AT-SOFTWARE."

Using bootstrap + SASS, it's possible to greatly improve the UI and overall feel of the site. For the most part, artistic and creative decisions will be left to the assignee's on this issue. Feel free to ask webmaster for input if unsure of something.

**Comment by andy-wojciechowski** [comment]
@GFLEMING133 @Joseph5062A  Another UX fix we could implement is this is how the post currently looks on my school computer.
![Capture](https://user-images.githubusercontent.com/31997141/62000453-e717e380-b09c-11e9-88c9-30ee680dbc46.PNG)
The submit button is too close to the bottom along with the markdown area being too close to the bottom as well. I originally implemented this on my personal desktop in which my resolution on that computer is 1600x900 so I don't know how we have less room on a computer that's 1920x1080?

**Comment by andy-wojciechowski** [comment]
@GFLEMING133 @rgeorgebu 
@Joseph5062A and I worked on some basic ux using more bootstrap classes around the editor and I think some UX feedback is needed before this issue is continued. The revised edit view is below.

![2](https://user-images.githubusercontent.com/31997141/62905452-2f3b3500-bd30-11e9-982b-3f80289da918.PNG)

I thought the SSE logo might be good to make the editor less plain and the form controls look a little bit better than the previous form controls. The toolbar was also modified to use bootstrap classes as well. Finally, the placeholders on the text fields was Joesph's idea. We thought it might be good especially to identify that the tags must be comma separated.

The validation messages and submission message also look way better.

![1](https://user-images.githubusercontent.com/31997141/62905692-2e56d300-bd31-11e9-8bef-85c8719728b9.PNG)

![3](https://user-images.githubusercontent.com/31997141/62905694-30b92d00-bd31-11e9-9413-16bb4c10e5e0.PNG)

What do you guys think of this page? Some of my thoughts are below but they're debatable.
1. Should we shrink the width of the validation messages and add a fade out behavior to them?
2. A lot of vertical space seems to being used. I'm not sure of the best way to handle that but one of my thoughts is we display some of the textbox fields together in a 2x2 grid or we can figure out how to display the label and the textbox field together in the same line.
3. The active style in bootstrap is not very noticeable. The markdown button is a little bit darker than the preview button, but it's not noticeable. I'm not sure if we can change that but there has gotta be a way.

There is also the list view. I have no thoughts on this view but I'd love some feedback on this page.
![4](https://user-images.githubusercontent.com/31997141/62905927-29465380-bd32-11e9-8ba0-becc234bb69d.PNG)

**Comment by GFLEMING133** [comment]
### My thoughts & responses:
1. Should we shrink the width of the validation messages and add a fade out behavior to them?
> Yes, I think that is a good thought,a nd you have some good suggestions as to how to fix. I'm happy to pull down and mess with some of the styling during our meeting on Wednesday if you like. 

2. A lot of vertical space seems to being used. I'm not sure of the best way to handle that but one of my thoughts is we display some of the textbox fields together in a 2x2 grid or we can figure out how to display the label and the textbox field together in the same line.
> Honestly, I think it's probably fine like this. That said, it isn't too hard with a flexbox or two to do what you're describing. Maybe @rgeorgebu can chime in on what UX standard here would be?

3. The active style in bootstrap is not very noticeable. The markdown button is a little bit darker than the preview button, but it's not noticeable. I'm not sure if we can change that but there has gotta be a way.
> Yep, there should be a way to change the shades of any given bootstrap color (https://getbootstrap.com/docs/4.3/utilities/colors/)

### OTHER COMMENTS
-----
I love the addition of the logo--branding is important, especially for a tool like this that org-external people will use. 
Giving the text placeholders is also an excellent idea @Joseph5062A! Love that addition.

**Comment by andy-wojciechowski** [comment]
@Joseph5062A I took point number 3 in Grace's feedback that background is now a little more noticeable. Can you please take point number 1 on Grace's feedback above. Let me know if you have any questions.
